package.json

- Changed npm start to be able to run es6 on heroku app
- Added dev dependencies into dependencies for heroku app
https://trello.com/c/0FylBbGv/6-heroku-deployment-create-heroku-repo

Heroku Deployment fixes

---

.gitignore
src/public/components/About.jsx
src/public/components/Contact.jsx
src/public/index.jsx
webpack.config.js

Create About and Contact pages

---

package.json
src/public/components/Admin.jsx
src/public/components/AdminPage.jsx
src/public/index.jsx

Admin Page

---

package.json
src/public/components/Student.jsx
src/public/components/UserPage.jsx
src/public/index.jsx

https://trello.com/c/TzJ4LpqS/43-create-user-component

Added User Page

---

src/public/components/AxiosRoutes.js
src/public/components/Student.jsx
src/server/app.js
src/server/db/config.js
src/server/db/search.js

https://trello.com/c/0rgGiV71/53-student-page-retrieving-information-from-the-database-upon-login

New data table added/ Retrieving information in Student Page

---

src/public/components/Student.jsx
src/server/app.js
src/server/db/search.js

Student Page Functionality Complete

---

src/server/cloudinary/cloudHelpers.js

Changed deconstructed variable names to match with data given.

[Hot Fix]Upload student photo

---

package.json
src/public/components/Routes.js
src/public/components/Student.js
src/public/components/index.js
src/server/app.js
src/server/db/config.js
src/server/db/search.js
src/server/twillio/twillioHelper.js
test/Student-test.js

Twillio able to send messages
https://trello.com/c/JIYUEyup/73-twilio-api

Added twillio

---

karma.conf.js
package.json
src/public/components/index.js
src/public/components/requests/classes.js
src/public/components/requests/students.js
test/CameraPage-test.js
test/Student-test.js
test/index-test.js

- All functionality being tested for App component now, including axios request stubbing.
- Commented out Student-test.js tests for now, need to fix some unhandled promise rejections somewhere in server files.

Full test coverage for App component

---

karma.conf.js
package.json
src/public/components/CameraPage.js
src/public/dist/index.html
src/server/app.js
src/server/auth/Auth0Helpers.js
src/server/db/search.js
src/server/db/userHelpers.js
src/server/kairosFR/kairosHelpers.js
webpack.config.js

https://trello.com/c/BkOExQ4R/93-camerapage-implement-dropdown-bar-to-track-which-classes-to-take-attendance-for
- Added css-loader for webpack / karma css transpiling for npm packages that need css files
- Added react-select multi select dropdown menu on camera page
- Added kairos.test function in preparation of testing facial recognition on picture capture
- Updated jQuery to 3.2.1
- Finished refactoring from callbacks into async / await methods

Implement class selection dropdown on CameraPage / Added css-loader support for karma/webpack

---

.eslintrc.js
package.json
src/public/components/AddStudent.js
src/public/components/CameraPage.js
src/public/components/Spinner.js
src/server/app.js
src/server/cloudinary/cloudHelpers.js
src/server/db/config.js
src/server/db/index.js
src/server/db/studentHelpers.js
src/server/kairosFR/kairosHelpers.js

https://trello.com/c/gzdPvTBa/96-fix-issure-where-duplicate-user-created-on-add-student
https://trello.com/c/4XThsZoF/95-implement-spinner-for-better-ux
- Added spinner component, conditionally renders when async requests are executing
- Fixed issue where duplicate user was getting stored on add student even if user already in DB
- Select user first, if get results returned, then do UPDATE instead of INSERT

Spinner / Fix duplicate user store

---

src/public/components/AddStudent.js
src/public/components/Admin.js
src/public/components/Student.js
src/public/components/helpers/tableHelpers.js
src/public/dist/index.html
src/public/dist/stylesheets/react-bootstrap-table.css
src/server/db/config.js
test/Admin-test.js
test/Student-test.js
test/tableHelpers-test.js

https://trello.com/c/Gl9UhZC4
https://trello.com/c/XrZyDpgq
https://trello.com/c/dTEldsRZ
https://trello.com/c/LAca31LF
https://trello.com/c/4ns0HrFh
https://trello.com/c/I4nvh8bH
https://trello.com/c/xwOeW53v
https://trello.com/c/3yivYGqC
Select menu for classes
Select menu for students
Select menu for statuses
Sort (custom) students by last name then first name
Sort (custom) dates
Test Admin component
Test Student component
Test tableHelpers
Refactor helper functions to separate file
Format addStudent page for visual consistence
Select user first, if get results returned, then do UPDATE instead of INSERT

Finish table and test it

---

src/server/app.js
src/server/db/config.js
src/server/db/search.js
src/server/kairosFR/kairosHelpers.js
src/server/mailgun/mailGunHelpers.js

https://trello.com/c/JIYUEyup/73-twilio-api-set-up-messaging-e-mail-ngrok

Upon checking in the login page user get send an email

---

src/server/db/config.js
src/server/db/index.js
src/server/mailgun/mailGunHelpers.js

https://trello.com/c/pdvAaEwm/126-mailgun-setting-up-domain-and-fixing-sending-of-emails
- Mail now sent from no-reply@mail.automatedattendance.com
- No longer need to worry about email verification, can send to any email address that passes email validation
- Refer to slack for updated mailgun API Keys

[Mailgun] - Mail working for unverified users

---

package.json
src/public/components/Admin.js
src/public/components/Enrollment.js
src/public/components/Routes.js
src/public/components/requests/classes.js
src/public/components/requests/students.js
test/Admin-test.js
test/Student-test.js
test/tableHelpers-test.js

https://trello.com/c/WUjMJOfC
https://trello.com/c/25U1AOrl
https://trello.com/c/4Q8A6JpZ
https://trello.com/c/N9CHqVhN
Create form for removing classes
Create form for removing students
More tests

Create form for removing students and classes

---

package.json
src/public/components/CameraPage.js
src/public/components/requests/students.js
src/server/app.js
src/server/db/insert.js
src/server/db/search.js
src/server/mailgun/mailGunHelpers.js

https://trello.com/c/zEmRNxv6/115-sending-late-message-to-all-users-who-are-late

Added Functionality to turn pending student to late and email them

---

src/public/components/Enrollment.js
src/server/db/ModelHelpers/classHelpers.js
src/server/db/ModelHelpers/studentHelpers.js
src/server/db/QueryModels/ClassModel.js
src/server/db/QueryModels/StudentModel.js
src/server/db/QuerySelectors/ClassQueries.js
src/server/db/QuerySelectors/StudentQueries.js

Check is class already exists when adding new class
Check if student is already enrolled when enrolling in class(es)
https://trello.com/c/aI8xRJMQ
https://trello.com/c/V7GcfeDh

Avoid duplicates in classes and class_user tables

---

src/server/db/ModelHelpers/studentHelpers.js
src/server/db/QueryModels/StudentModel.js
src/server/db/QuerySelectors/StudentQueries.js

#Trello Ticket
https://trello.com/c/NDlf7Wa6/137-update-user-in-db-to-checked-in-on-successful-fr
- Update matched users attendance record to 'On time' when checked in successfully

Update to On time in DB when facial recognition returns valid matches

---

src/server/db/QueryModels/StudentModel.js

Reverts Automated-Attendance/AutomatedAttendance#69

Revert "[fix] upload checkinOnTime function that didnt get merged"

---

src/server/db/ModelHelpers/studentHelpers.js
src/server/db/QueryModels/StudentModel.js
src/server/db/QuerySelectors/StudentQueries.js
src/server/db/config.js
src/server/kairosFR/kairosHelpers.js

and changed DB schema to not insert MYSQL default current timestamp

[Update Time] insert moment time object 

---

package.json
src/public/components/Admin.js
src/public/components/CameraPage.js
src/public/components/Enrollment.js
src/public/components/LoginRedirect.js
src/public/components/Student.js
src/public/components/requests/students.js
src/server/db/config.js
test/LoginRedirect-test.js

https://trello.com/c/fK92HgL5
https://trello.com/c/JIVmCaIX
https://trello.com/c/paS2zaGr
Also update select menus to show dynamic changes

Create form for changing attendance status, include student/class names in confirmations

---

src/public/components/Admin.js
src/public/components/Student.js
src/public/components/helpers/tableHelpers.js
src/server/db/QuerySelectors/AttendanceQueries.js
test/tableHelpers-test.js

https://trello.com/c/GskF8tTW
https://trello.com/c/BpNatUCT

Fix populate attendance records and use Moment time objects everywhere

---

src/server/db/QuerySelectors/StudentQueries.js

Fixed check-in page

---

src/public/components/Admin.js
src/public/components/requests/students.js
src/server/app.js
src/server/db/ModelHelpers/attendanceHelpers.js
src/server/db/QueryModels/AttendanceModel.js
src/server/db/QuerySelectors/AttendanceQueries.js

https://trello.com/c/JowYUGne/155-admin-page-functionality-all-done

Admin Page functionality done

---

src/server/db/QueryModels/AttendanceModel.js

[Fix Duplicates] Prevent multiple additions of students on the same day

---

src/server/db/ModelHelpers/studentHelpers.js
src/server/db/QueryModels/StudentModel.js
src/server/db/QuerySelectors/StudentQueries.js

[Check in Tardy] Check in as tardy if student arrives after cutoff time

---

src/public/components/About.js
src/public/components/Contact.js
src/server/db/index.js
src/server/index.js

https://trello.com/c/gQNR1rbt
https://trello.com/c/HdA32JKk

Fill in About and Contact page

---

README.md
src/public/components/About.js
src/public/components/Admin.js
src/public/components/Camera.js
src/public/components/CameraPage.js
src/public/components/Contact.js
src/public/components/EditAttendance.js
src/public/components/Enrollment.js
src/public/components/LandingPage/Testimonials.js
src/public/components/Navigation.js
src/public/components/Routes.js
src/public/components/StartAttendance.js
src/public/components/Student.js
src/public/components/tables/EnrollmentTable.js
src/public/requests/classes.js
test/FrontEndTests/About-test.js
test/FrontEndTests/Admin-test.js
test/FrontEndTests/Camera-test.js
test/FrontEndTests/Enrollment-test.js
test/FrontEndTests/Navigation-test.js
test/FrontEndTests/Student-test.js
test/FrontEndTests/ToggleStatus-test.js

#Trello
https://trello.com/c/Qe3vBWDD
https://trello.com/c/o7UEEg5g

Refactoring front end
